comment out compress

diff --git a/tasks/internal/push-artifacts-to-cdn-task/push-artifacts-to-cdn-task.yaml b/tasks/internal/push-artifacts-to-cdn-task/push-artifacts-to-cdn-task.yaml
--- a/tasks/internal/push-artifacts-to-cdn-task/push-artifacts-to-cdn-task.yaml
+++ b/tasks/internal/push-artifacts-to-cdn-task/push-artifacts-to-cdn-task.yaml
@@ -826,81 +826,81 @@ spec:
 
         mv "$SHA_SUM_PATH" "${SIGNED_DIR}/sha256sum.txt"
 
-    - name: compress-artifacts
-      image: quay.io/konflux-ci/release-service-utils:937662a1ba4b345d3bd1f64b13ead1c31e7ac473
-      computeResources:
-        limits:
-          memory: 256Mi
-        requests:
-          memory: 256Mi
-          cpu: 150m
-      volumeMounts:
-        - name: shared-dir
-          mountPath: /shared
-      env:
-        - name: "SNAPSHOT_JSON"
-          value: "$(params.snapshot_json)"
-      script: |
-        #!/usr/bin/env bash
-        set -eu
+    # - name: compress-artifacts
+    #   image: quay.io/konflux-ci/release-service-utils:937662a1ba4b345d3bd1f64b13ead1c31e7ac473
+    #   computeResources:
+    #     limits:
+    #       memory: 256Mi
+    #     requests:
+    #       memory: 256Mi
+    #       cpu: 150m
+    #   volumeMounts:
+    #     - name: shared-dir
+    #       mountPath: /shared
+    #   env:
+    #     - name: "SNAPSHOT_JSON"
+    #       value: "$(params.snapshot_json)"
+    #   script: |
+    #     #!/usr/bin/env bash
+    #     set -eu
 
-        STDERR_FILE=/tmp/stderr.txt
+    #     STDERR_FILE=/tmp/stderr.txt
 
-        # Check if the previous step finished successfully. If not, stop here.
-        if [ "$(cat "$(results.result.path)")" != "Success" ]; then
-          echo "Previous step failed. Exiting..."
-          exit 0
-        fi
+    #     # Check if the previous step finished successfully. If not, stop here.
+    #     if [ "$(cat "$(results.result.path)")" != "Success" ]; then
+    #       echo "Previous step failed. Exiting..."
+    #       exit 0
+    #     fi
 
-        exitfunc() {
-            local err=$1
-            local line=$2
-            local command="$3"
-            if [ "$err" -eq 0 ] ; then
-                echo -n "Success" > "$(results.result.path)"
-            else
-                echo "$0: ERROR '$command' failed at line $line - exited with status $err" > "$(results.result.path)"
-                if [ -f "$STDERR_FILE" ] ; then
-                    # save output to the task result excluding the trace log
-                    grep -v "^\+" "$STDERR_FILE" | tail -c 512 | tee -a "$(results.result.path)"
-                fi
-            fi
-            exit 0 # exit the script cleanly as there is no point in proceeding past an error or exit call
-        }
-        # due to set -e, this catches all EXIT and ERR calls and the task should never fail with nonzero exit code
-        # trap 'exitfunc $? $LINENO "$BASH_COMMAND"' EXIT
+    #     exitfunc() {
+    #         local err=$1
+    #         local line=$2
+    #         local command="$3"
+    #         if [ "$err" -eq 0 ] ; then
+    #             echo -n "Success" > "$(results.result.path)"
+    #         else
+    #             echo "$0: ERROR '$command' failed at line $line - exited with status $err" > "$(results.result.path)"
+    #             if [ -f "$STDERR_FILE" ] ; then
+    #                 # save output to the task result excluding the trace log
+    #                 grep -v "^\+" "$STDERR_FILE" | tail -c 512 | tee -a "$(results.result.path)"
+    #             fi
+    #         fi
+    #         exit 0 # exit the script cleanly as there is no point in proceeding past an error or exit call
+    #     }
+    #     # due to set -e, this catches all EXIT and ERR calls and the task should never fail with nonzero exit code
+    #     # trap 'exitfunc $? $LINENO "$BASH_COMMAND"' EXIT
 
-        CONTENT_DIR=/shared/artifacts
-        COMPRESSED_DIR="$CONTENT_DIR/compressed"
+    #     CONTENT_DIR=/shared/artifacts
+    #     COMPRESSED_DIR="$CONTENT_DIR/compressed"
 
-        function compress_components {
-          mkdir -p "$COMPRESSED_DIR"
-          COMPONENT_JSON="$1"
-          NUM_MAPPED_FILES=$(jq '.files | length' <<< "${COMPONENT_JSON}")
-          for ((i = 0; i < NUM_MAPPED_FILES; i++)) ; do
-            FILE=$(jq -c --arg i "$i" '.files[$i|tonumber]' <<< "$COMPONENT")
-            SOURCE=$(jq -er '.source' <<< "$FILE") \
-              || (echo "Missing files.source for component." && exit 1 )
-            BINARY=$(jq -er '.binary' <<< "$FILE")
-            case "${SOURCE}" in
-              (*darwin*)
-                tar -czf "${COMPRESSED_DIR}/${SOURCE}" -r "macos/${BINARY}"
-                ;;
-              (*linux*)
-                tar -czf "${COMPRESSED_DIR}/${SOURCE}" -r "linux/${BINARY}"
-                ;;
-              (*windows*)
-                zip -r "${COMPRESSED_DIR}/${SOURCE}" "windows/${BINARY}"
-                ;;
-            esac
-          done
-        }
+    #     function compress_components {
+    #       mkdir -p "$COMPRESSED_DIR"
+    #       COMPONENT_JSON="$1"
+    #       NUM_MAPPED_FILES=$(jq '.files | length' <<< "${COMPONENT_JSON}")
+    #       for ((i = 0; i < NUM_MAPPED_FILES; i++)) ; do
+    #         FILE=$(jq -c --arg i "$i" '.files[$i|tonumber]' <<< "$COMPONENT")
+    #         SOURCE=$(jq -er '.source' <<< "$FILE") \
+    #           || (echo "Missing files.source for component." && exit 1 )
+    #         BINARY=$(jq -er '.binary' <<< "$FILE")
+    #         case "${SOURCE}" in
+    #           (*darwin*)
+    #             tar -czf "${COMPRESSED_DIR}/${SOURCE}" -r "macos/${BINARY}"
+    #             ;;
+    #           (*linux*)
+    #             tar -czf "${COMPRESSED_DIR}/${SOURCE}" -r "linux/${BINARY}"
+    #             ;;
+    #           (*windows*)
+    #             zip -r "${COMPRESSED_DIR}/${SOURCE}" "windows/${BINARY}"
+    #             ;;
+    #         esac
+    #       done
+    #     }
 
-        NUM_COMPONENTS=$(jq '.components | length' <<< "$SNAPSHOT_JSON")
-        for ((c = 0; c < NUM_COMPONENTS; c++)) ; do
-            COMPONENT=$(jq -c --arg i "$c" '.components[$i|tonumber]' <<< "$SNAPSHOT_JSON")
-            compress_components "$COMPONENT" 2> "$STDERR_FILE"
-        done
+    #     NUM_COMPONENTS=$(jq '.components | length' <<< "$SNAPSHOT_JSON")
+    #     for ((c = 0; c < NUM_COMPONENTS; c++)) ; do
+    #         COMPONENT=$(jq -c --arg i "$c" '.components[$i|tonumber]' <<< "$SNAPSHOT_JSON")
+    #         compress_components "$COMPONENT" 2> "$STDERR_FILE"
+    #     done
 
     - name: push-artifacts
       image: quay.io/konflux-ci/release-service-utils:937662a1ba4b345d3bd1f64b13ead1c31e7ac473
